version: '3.8'

services:
  # Serviço do Banco de Dados (MySQL)
  db:
    image: mysql:8.0
    container_name: darkaccess-db-mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD} # Pega a senha de um arquivo .env
    ports:
      - "3306:3306"
    volumes:
      - darkaccess-mysql-data:/var/lib/mysql

  # Serviço da nossa API (Back-End)
  api:
    build: ./Back-End # Diz ao Compose para construir a imagem a partir do Dockerfile na pasta Back-End
    container_name: darkaccess-api
    restart: always
    ports:
      - "3001:3001"
    volumes:
      - ./Back-End:/app # Espelha o código local para dentro do contêiner (ótimo para desenvolver)
      - /app/node_modules
    depends_on:
      - db # Garante que a API só vai iniciar depois que o banco de dados estiver pronto
    environment:
      DATABASE_URL: mysql://root:${DB_PASSWORD}@db:3306/darkaccess_dev # String de conexão

# Define o volume para persistência do banco de dados
volumes:
  darkaccess-mysql-data: