# --- ESTÁGIO 1: Build (Construção) ---
FROM node:18-alpine AS build
WORKDIR /app
COPY package.json ./
COPY package-lock.json ./
RUN npm install
COPY . .
RUN npm run build

# --- ESTÁGIO 2: Production (Produção) ---
FROM nginx:stable-alpine

# Copia os arquivos compilados do estágio de build para a pasta padrão do Nginx
COPY --from=build /app/build /usr/share/nginx/html

# AQUI ESTÁ A MUDANÇA: Remove a configuração padrão do Nginx...
RUN rm /etc/nginx/conf.d/default.conf

# ...E copia a nossa configuração customizada para o lugar dela.
COPY nginx.conf /etc/nginx/conf.d

EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]